coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "crates/nblm-python/**/*"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

