[config]
skip_core_tasks = true
default_to_workspace = false

[env]

[tasks.before-build]

[tasks.default]
description = "Default task"
dependencies = ["fmt", "lint", "check"]

[tasks.fmt]
description = "Apply rustfmt to all projects"
command = "cargo"
args = ["fmt", "--all"]

[tasks.fmt-ci]
description = "Verify formatting"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.lint]
description = "Verify zero clippy warnings"
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.test]
description = "Run test suite"
command = "cargo"
args = ["test", "--all"]

[tasks.check]
dependencies = ["before-build"]
command = "cargo"
args = ["check", "--all"]

[tasks.build]
dependencies = ["before-build"]
command = "cargo"
args = ["build", "${@}"]

[tasks.clean]
dependencies = ["before-build"]
command = "cargo"
args = ["clean"]

[tasks.fetch]
dependencies = ["before-build"]
command = "cargo"
args = ["fetch"]

[tasks.coverage]
description = "Generate coverage report using cargo-llvm-cov"
dependencies = ["before-build"]
command = "cargo"
args = ["llvm-cov", "--workspace", "--all-features", "--open"]

[tasks.all]
description = "Run fmt, lint, and test together"
dependencies = ["fmt", "lint", "test"]

# ------------------------- CI -------------------------
[tasks.ci]
description = "Run CI checks (fmt, clippy, tests)"
dependencies = ["fmt-ci", "clippy-ci", "test-ci"]

[tasks.clippy-ci]
extend = "set-env-local"
dependencies = ["before-build"]
command = "cargo"
args = ["clippy", "--locked", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.test-ci]
dependencies = ["before-build"]
command = "cargo"
args = ["test", "--locked", "--workspace", "--all-targets"]
