[package]
name = "nblm-python"
version = "0.1.3"
edition = "2021"
license = "MIT"
description = "Python bindings for nblm-core (NotebookLM Enterprise API client)"
repository = "https://github.com/K-dash/nblm-rs"
homepage = "https://github.com/K-dash/nblm-rs"
readme = "../../README.md"
keywords = ["notebooklm", "api", "google-cloud", "gemini", "python"]
categories = ["api-bindings"]
authors = ["K-dash"]

[lib]
name = "nblm"
crate-type = ["cdylib"]

[dependencies]
nblm-core = { path = "../nblm-core" }
pyo3 = { version = "0.23", features = ["extension-module", "abi3-py312"] }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0"
mime_guess = "2.0.5"
